
/*=====================================*/
/* oracle sql */
/*=====================================*/

DROP TABLE D_USER CASCADE CONSTRAINTS;
DROP TABLE D_USERGROUP CASCADE CONSTRAINTS;
DROP TABLE D_USERGROUP_REL CASCADE CONSTRAINTS;
DROP TABLE D_FOOD CASCADE CONSTRAINTS;
DROP TABLE D_FOOD_DIC CASCADE CONSTRAINTS;
DROP TABLE D_ORDER CASCADE CONSTRAINTS;
DROP TABLE D_ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE D_ORDERDIC_REL CASCADE CONSTRAINTS;
DROP TABLE D_PARAM CASCADE CONSTRAINTS;
DROP TABLE D_MONEY CASCADE CONSTRAINTS;


-- 1. D_USER

CREATE TABLE D_USER(
	USERUUID   	VARCHAR2(50)	NOT NULL,
	EMAIL 		VARCHAR2(100),
	USERNAME	VARCHAR2(100),
	PASSWORD	VARCHAR2(100),
	STATUS		VARCHAR2(2),
	USERNOMBER	VARCHAR2(50),
	CONSTRAINT DUSER_PK PRIMARY KEY (USERUUID)
)

-- 2. D_USERGROUP

CREATE TABLE D_USERGROUP(
	GROUPUUID	VARCHAR2(50)	NOT NULL,
	GROUPNAME	VARCHAR2(50),
	CONSTRAINT DUSERGROUP_PK PRIMARY KEY (GROUPUUID)
)

-- 3. D_USERGROUP_REL

CREATE TABLE D_USERGROUP_REL(
	GURELUUID	VARCHAR2(50)	NOT NULL,
	GROUPUUID	VARCHAR2(50)	NOT NULL,
	USERUUID	VARCHAR2(50)	NOT NULL,
	CONSTRAINT DUSERGROUPREL_PK PRIMARY KEY (GURELUUID),
	CONSTRAINT DUSERGROUP_FK FOREIGN KEY (GROUPUUID) REFERENCES D_USERGROUP (GROUPUUID),
	CONSTRAINT DUSER_FK FOREIGN KEY (USERUUID) REFERENCES D_USER (USERUUID)
)

-- 4. D_FOOD

CREATE TABLE D_FOOD(
	FOODUUID	VARCHAR2(50)	NOT NULL,
	FOODNAME	VARCHAR2(50),
	FOODPRICE	NUMBER(5,2),
	FOODNUM		NUMBER,
	STATUS		VARCHAR2(2),
	FOODRES		VARCHAR2(50),
	CONSTRAINT DFOOD_PK PRIMARY KEY (FOODUUID)
)


-- 5. D_FOOD_DIC

CREATE TABLE D_FOOD_DIC(
	DICUUID		VARCHAR2(50)	NOT NULL,
	DICNAME		VARCHAR2(50),
	FOODUUID	VARCHAR2(50),
	STATUS		VARCHAR2(2)		NOT NULL,
	CONSTRAINT DFOODDIC_PK PRIMARY KEY (DICUUID),
	CONSTRAINT DFOOD1_FK FOREIGN KEY (FOODUUID) REFERENCES D_FOOD (FOODUUID) ON DELETE CASCADE ENABLE
)

-- 6. D_ORDER

CREATE TABLE D_ORDER(
	ORDERUUID	VARCHAR2(50)	NOT NULL,
	USERUUID	VARCHAR2(50)	NOT NULL,
	TOTAL		NUMBER(5,2),
	ORDERDATE	VARCHAR2(50),
	STATUS		VARCHAR2(50),
	ORDERSEQ	VARCHAR2(200),
	CONSTRAINT DORDER_PK PRIMARY KEY (ORDERUUID),
	CONSTRAINT DUSER1_FK  FOREIGN KEY (USERUUID) REFERENCES D_USER (USERUUID) ENABLE
)

-- 7. D_ORDER_DETAIL

CREATE TABLE D_ORDER_DETAIL(
	DETAILUUID		VARCHAR2(50)	NOT NULL,
	ORDERUUID		VARCHAR2(50)	NOT NULL,
	FOODUUID		VARCHAR2(50)	NOT NULL,
	DETAILNUM		NUMBER,
	CONSTRAINT DORDERDETAIL_PK 	PRIMARY KEY (DETAILUUID),
	CONSTRAINT DFOOD2_FK 	FOREIGN KEY (FOODUUID) REFERENCES D_FOOD (FOODUUID) ENABLE, 
	CONSTRAINT DORDER_FK 		FOREIGN KEY (ORDERUUID) REFERENCES D_ORDER (ORDERUUID) ON DELETE CASCADE ENABLE
）

-- 8. D_ORDERDIC_REL

CREATE TABLE D_ORDERDIC_REL(
	ORDICUUID		VARCHAR2(50)	NOT NULL,
	DETAILUUID		VARCHAR2(50)	NOT NULL,
	DICUUID			VARCHAR2(50)	NOT NULL,
	ORDICNUM		NUMBER 		 	NOT NULL,
	CONSTRAINT DORDERDICREL_PK PRIMARY KEY (ORDICUUID),
	CONSTRAINT DFOODDIC_FK FOREIGN KEY (DICUUID) REFERENCES D_FOOD_DIC (DICUUID) ENABLE,
	CONSTRAINT DORDERDETAIL_FK FOREIGN KEY (DETAILUUID) REFERENCES D_ORDER_DETAIL (DETAILUUID) ON DELETE CASCADE ENABLE
)

-- 9. D_PARAM

CREATE TABLE D_PARAM(
	PARAMUUID	VARCHAR2(50)	NOT NULL,
	PARAMCODE	VARCHAR2(50)	NOT NULL,
	PARAMENAME	VARCHAR2(50),
	PARAMDIS	VARCHAR2(1000),
	PARAMVALUE	VARCHAR2(100)	NOT NULL,
 	CONSTRAINT DPARAM_PK PRIMARY KEY (PARAMUUID)
)

-- 10. D_MONEY

CREATE TABLE D_MONEY(
	MONEYUUID	VARCHAR2(50)	NOT NULL,
	MONEYVALUE	NUMBER(5,2),
	USERUUID	VARCHAR2(50)	NOT NULL,
	CONSTRAINT DMONEY_PK PRIMARY KEY (MONEYUUID),
	CONSTRAINT DUSER2_FK FOREIGN KEY (USERUUID) REFERENCES D_USER (USERUUID) ENABLE
)
